"""
Module to mask and score samples generated by CorrDiff.

This module exposes the high-level functions and constants required for
mask and score model outputs, without requiring callers to import from
internal implementation modules.

It provides:
- Dataset masking utilities for preparing generation inputs.
- Time-stamped logging helpers.
- Single- and multi-ensemble scoring entrypoints for computing
  verification metrics (e.g., RMSE, MAE, CRPS).
- Shared evaluation constants used across plotting and reporting code.
"""
from .masking import save_masked_samples, get_timestamp
from .scoring import score_samples, score_samples_multi_ensemble, N_YEARS

__all__ = [
    "save_masked_samples",      "get_timestamp",
    "score_samples",            "score_samples_multi_ensemble",

    "N_YEARS",
]
